# Server configurations
server:
  host: "localhost"
  port: ":3000"

# Cloudfront configurations
cloudfront:
  url: "https://example.cloudfront.net"
  key_id: "K1HFGXOMBB6TFF"
  private_key: |
    -----BEGIN PRIVATE KEY-----
    development key content here
    -----END PRIVATE KEY-----

# TLS configurations (mTLS support)
tls:
  enabled: false
  cert_file: "/path/to/server.crt"
  key_file: "/path/to/server.key"
  ca_file: "/path/to/ca.crt"
  client_auth: "none"  # Options: "none", "request", "require", "verify-if-given", "require-and-verify"
  min_version: "1.2"   # Options: "1.0", "1.1", "1.2", "1.3"
  max_version: "1.3"   # Options: "1.0", "1.1", "1.2", "1.3"
