name: Tests

on: ["push", "pull_request"]

jobs:
  tests:
    name: "Go ${{ matrix.go.series }}"
    runs-on: "ubuntu-24.04"

    strategy:
      matrix:
        go:
          # Keep minimum version up to date with go.mod
          - series: "1.24"
            version: "1.24.2"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go.version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go.version }}

    - name: Cache Go modules
      uses: "actions/cache@v4"
      with:
        path: cache
        key: "go=${{ matrix.go.version }};v=1"

    - name: Build binary
      run: go build -v -o munkisrv ./cmd/munkisrv

    - name: Test binary execution
      run: |
        # Test that the binary can start and parse config
        timeout 5s ./munkisrv -c config/config.yaml || true

  integration:
    name: Integration Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go:
          # Keep minimum version up to date with go.mod
          - series: "1.24"
            version: "1.24.2"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go.version }}

    - name: Download dependencies
      run: go mod download

    - name: Build binary
      run: go build -v -o munkisrv ./cmd/munkisrv

    - name: Create test config
      run: |
        cat > test-config.yaml << EOF
        server:
          host: "localhost"
          port: ":8080"
        cloudfront:
          url: "https://test.cloudfront.net"
          key_id: "K1HFGXOMBB6TFF"
          private_key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIEpAIBAAKCAQEAvxJndkREqFkXg2b6QRNCxYy67Kj/tQfR5tGP1k18wgInS8W6
            vxwhAIr9JdhVjIkyRfn13eM9kqH8ky5UkiCP0cbxVkHgSdYUWyaqAqBQDSH6vr9R
            icbo6c2APVWf8VjUxhyzK6tWHnKEZEP2bY2Y22E9lQm8nucEs3P0uYIx1hEx+d6
            WE1FkP7L6PWSsn6twhQ3VW0WmLuFQbQ1tFuyigMxAGcxz+CsxLnMo7OGtHrqC7an
            QgxLkq8atpoexi0nebdRZgxwhFFCIo9XgRBU7Q1VX5Pj1VstscRxlMCz0mxvuapi
            rLu2RAdD8m6jwpw1F1QHRCQIDAQABAoIBAQCm5inobyE5GRKHOnVXBN+9QqSenNL
            i+ZlO+CyExH6yWGoeW81F4m5FWzpM2O/f0S31thI9i+1K5tn8jqu4CywujUxddXG
            VjrypLVngk5y4j5P5WdwZkJlxtVqtVK6ZxBLp7eCdbL0U9EtJTaS4/4Sg3MjyvIq
            GtkR64fuRkHdjLqUi3goZUUgl1Hb7j4W3BuL6xwSxM7aKjGZHbXZxJz9UZ8V7jqW
            QZxJjLWjTRf6AlwjBp4Z7hKhm4E6aRfwtCg7XaFz8J4y4I4Q4I4Q4I4Q4I4Q4I4Q
            4I4Q4I4Q4I4Q4I4Q4I4Q4I4Q4I4Q4I4Q4I4Q4I4Q4I4Q4I4Q4I4Q4I4Q4I4Q4I4Q
            -----END RSA PRIVATE KEY-----
        EOF

    - name: Start server in background
      run: |
        ./munkisrv -c test-config.yaml &
        SERVER_PID=$!
        echo $SERVER_PID > server.pid
        sleep 3

    - name: Test health endpoint
      run: |
        curl -f http://localhost:8080/healthz || exit 1

    - name: Test repository endpoint
      run: |
        curl -f http://localhost:8080/repo/catalogs/all || exit 1

    - name: Stop server
      run: |
        if [ -f server.pid ]; then
          kill $(cat server.pid) || true
        fi
      if: always() 
